In [1]:
import pandas as pd
#import matplotlib.pyplot as plt
#import numpy as np

Usei a função read_csv para importar o arquivo, realizarei a limpeza das informações que desejo trabalhar na análise de dados.

In [2]:
df_consentido_pais = pd.read_csv('datasets/consentido_pais.csv')
df_consentido_pais

,ID do indicador,descrição do indicador,descrição da série de mentalidade,area de referencia,descrição da area de refêrencia,iso3,x,y,região ODS,sexo,...,detalhe de tempo,modificador de valor obs,valor de observação,nature,observação de comentários,source_detail,source_detail_url,source_year,dimensions,is_latest_year
0,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,8,Albânia,ALB,2.006.660.928,4.113.897.007,Europa e América do Norte,M,...,2012-2021,<,18.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
1,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,8,Albânia,ALB,2.006.660.928,4.113.897.007,Europa e América do Norte,F,...,2012-2021,<,18.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
2,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,20,Andorra,AND,1.576.257.417,4.254.548.611,Europa e América do Norte,M,...,2012-2021,NaN,14.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
3,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,20,Andorra,AND,1.576.257.417,4.254.548.611,Europa e América do Norte,F,...,2012-2021,NaN,14.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
4,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,660,Anguila,AIA,-6.305.651.612,1.821.525.315,América Latina e Caribe,M,...,2012-2021,NaN,16.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,860,Uzbequistão,UZB,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,...,2012-2021,NaN,18.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
187,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,862,Venezuela (República Bolivariana da),VEN,-6.615.642.084,7.121.324.748,América Latina e Caribe,M,...,2012-2021,NaN,16.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
188,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,862,Venezuela (República Bolivariana da),VEN,-6.615.642.084,7.121.324.748,América Latina e Caribe,F,...,2012-2021,NaN,14.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
189,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,716,Zimbábue,ZWE,2.986.909.584,-1.900.075.492,África Subsaariana,M,...,2012-2021,NaN,16.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1
190,Ifdb90d43,Idade mínima legal para casar por sexo,Idade mínima para casamento legal - Com consen...,716,Zimbábue,ZWE,2.986.909.584,-1.900.075.492,África Subsaariana,F,...,2012-2021,NaN,16.0,C,NaN,Demographic Yearbook 2021,https://unstats.un.org/unsd/demographic-social...,2022,sex,1

In [3]:
df_consentido_pais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID do indicador                    191 non-null    object
 1   descrição do indicador             191 non-null    object
 2   descrição da série de mentalidade  191 non-null    object
 3   area de referencia                 191 non-null    int64
 4   descrição da area de refêrencia    191 non-null    object
 5   iso3                               191 non-null    object
 6   x                                  191 non-null    object
 7   y                                  191 non-null    object
 8   região ODS                         191 non-null    object
 9   sexo                               191 non-null    object
 10  descrição de sexo                  191 non-null    object
 11  período de tempo                   191 non-null    int64
 12  detalhe de tempo                   191 non-null    object
 13  modificador de valor obs           12 non-null     object
 14  valor de observação                191 non-null    float64
 15  nature                             191 non-null    object
 16  observação de comentários          48 non-null     object
 17  source_detail                      191 non-null    object
 18  source_detail_url                  191 non-null    object
 19  source_year                        191 non-null    int64
 20  dimensions                         191 non-null    object
 21  is_latest_year                     191 non-null    int64
dtypes: float64(1), int64(4), object(17)
memory usage: 33.0+ KB

In [4]:
import pandas as pd

df_consentido_pais.isnull()

,ID do indicador,descrição do indicador,descrição da série de mentalidade,area de referencia,descrição da area de refêrencia,iso3,x,y,região ODS,sexo,...,detalhe de tempo,modificador de valor obs,valor de observação,nature,observação de comentários,source_detail,source_detail_url,source_year,dimensions,is_latest_year
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
187,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
188,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
189,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
190,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False

In [5]:
df_consentido_pais.isnull().sum()

ID do indicador                        0
descrição do indicador                 0
descrição da série de mentalidade      0
area de referencia                     0
descrição da area de refêrencia        0
iso3                                   0
x                                      0
y                                      0
região ODS                             0
sexo                                   0
descrição de sexo                      0
período de tempo                       0
detalhe de tempo                       0
modificador de valor obs             179
valor de observação                    0
nature                                 0
observação de comentários            143
source_detail                          0
source_detail_url                      0
source_year                            0
dimensions                             0
is_latest_year                         0
dtype: int64

                                           Analisando os dados
                                           
Começando nossa análise exploratória, farei a exclusão de algumas colunas que não irão interferir no resultado da análise.

Tentei usar a função drop, excluia as colunas mas não imprimia. Entaão, identifiquei as colunas que eu queria excluir coma função df.columns e criando um novo DataFrame com as informaçoes que eu precisava.

Excluindo as seguintes colunas: 
ID do indicador, descrição do indicador, descrição da série de mentalidade, isos3, source_detail_url,dimensions, is_latest_year.

In [6]:
df_consentido_pais.columns

Index(['ID do indicador', 'descrição do indicador',
       'descrição da série de mentalidade', 'area de referencia',
       'descrição da area de refêrencia', 'iso3', 'x', 'y', 'região ODS',
       'sexo', 'descrição de sexo', 'período de tempo', 'detalhe de tempo',
       'modificador de valor obs', 'valor de observação', 'nature',
       'observação de comentários', 'source_detail', 'source_detail_url',
       'source_year', 'dimensions', 'is_latest_year'],
      dtype='object')

In [26]:
df_consentido = df_consentido_pais[['descrição da area de refêrencia', 'x', 'y', 'região ODS', 
              'sexo', 'detalhe de tempo', 'modificador de valor obs','valor de observação', 'observação de comentários', 'source_year']]
df_consentido

,descrição da area de refêrencia,x,y,região ODS,sexo,detalhe de tempo,modificador de valor obs,valor de observação,observação de comentários,source_year
0,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,2012-2021,<,18.0,NaN,2022
1,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,F,2012-2021,<,18.0,NaN,2022
2,Andorra,1.576.257.417,4.254.548.611,Europa e América do Norte,M,2012-2021,NaN,14.0,NaN,2022
3,Andorra,1.576.257.417,4.254.548.611,Europa e América do Norte,F,2012-2021,NaN,14.0,NaN,2022
4,Anguila,-6.305.651.612,1.821.525.315,América Latina e Caribe,M,2012-2021,NaN,16.0,NaN,2022
...,...,...,...,...,...,...,...,...,...,...
186,Uzbequistão,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,2012-2021,NaN,18.0,NaN,2022
187,Venezuela (República Bolivariana da),-6.615.642.084,7.121.324.748,América Latina e Caribe,M,2012-2021,NaN,16.0,NaN,2022
188,Venezuela (República Bolivariana da),-6.615.642.084,7.121.324.748,América Latina e Caribe,F,2012-2021,NaN,14.0,NaN,2022
189,Zimbábue,2.986.909.584,-1.900.075.492,África Subsaariana,M,2012-2021,NaN,16.0,NaN,2022
190,Zimbábue,2.986.909.584,-1.900.075.492,África Subsaariana,F,2012-2021,NaN,16.0,NaN,2022

In [8]:
# os países em que o casamento é permitido com meninas de idade inferior a 15 anos?
# Na américa latina, qual a idade para casamento legalizado?
# Quais os países na América Latina em que ocorrem casos com de casamentos com o consetimento dos pais.
# Quais os 15 países no mundo com maior incidencia de casamentos antes dos 18 anos de idade.

In [9]:
df_consentimento_negado = pd.read_csv('datasets/consentimento_negado.csv')
df_consentimento_negado

,indicator_label,descrição do indicador,descrição da série de mentalidade,area de referencia,x,y,região ODS,sexo,descrição de sexo,período de tempo,detalhe de tempo,valor de observação,observação de comentários,source_detail_url,ano de origem
0,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Ilhas Aland,1.980.945.969,601.544.901,Europa e América do Norte,M,Macho,2021,2012-2021,18.0,Pessoas com menos de 18 anos precisam de autor...,https://unstats.un.org/unsd/demographic-social...,2022
1,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Ilhas Aland,1.980.945.969,601.544.901,Europa e América do Norte,F,Femea,2021,2012-2021,18.0,Pessoas com menos de 18 anos precisam de autor...,https://unstats.un.org/unsd/demographic-social...,2022
2,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,Macho,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
3,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,F,Femea,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
4,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Andorra,1.576.257.417,4.254.548.611,Europa e América do Norte,M,Macho,2021,2012-2021,16.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Venezuela (República Bolivariana da),-6.615.642.084,7.121.324.748,América Latina e Caribe,F,Female,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
251,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Vietnã,105.802.499,1.009.643.079,Leste e Sudeste Asiático,M,Male,2021,2012-2021,20.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
252,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Vietnã,105.802.499,1.009.643.079,Leste e Sudeste Asiático,F,Female,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
253,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Zimbábue,2.986.909.584,-1.900.075.492,África Subsaariana,M,Male,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
254,QV.4,Idade mínima legal para casar por sexo,Idade mínima para casamento legal – Sem consen...,Zimbábue,2.986.909.584,-1.900.075.492,África Subsaariana,F,Female,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022

In [10]:
df_consentimento_negado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   indicator_label                    255 non-null    object
 1   descrição do indicador             255 non-null    object
 2   descrição da série de mentalidade  255 non-null    object
 3   area de referencia                 255 non-null    object
 4   x                                  255 non-null    object
 5   y                                  255 non-null    object
 6   região ODS                         255 non-null    object
 7   sexo                               255 non-null    object
 8   descrição de sexo                  255 non-null    object
 9   período de tempo                   255 non-null    int64
 10  detalhe de tempo                   255 non-null    object
 11  valor de observação                255 non-null    float64
 12  observação de comentários          84 non-null     object
 13  source_detail_url                  255 non-null    object
 14  ano de origem                      255 non-null    int64
dtypes: float64(1), int64(2), object(12)
memory usage: 30.0+ KB

In [11]:
df_consentimento_negado.isnull()

,indicator_label,descrição do indicador,descrição da série de mentalidade,area de referencia,x,y,região ODS,sexo,descrição de sexo,período de tempo,detalhe de tempo,valor de observação,observação de comentários,source_detail_url,ano de origem
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
251,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
252,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
253,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
254,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [12]:
df_consentimento_negado.isnull().sum()

indicator_label                        0
descrição do indicador                 0
descrição da série de mentalidade      0
area de referencia                     0
x                                      0
y                                      0
região ODS                             0
sexo                                   0
descrição de sexo                      0
período de tempo                       0
detalhe de tempo                       0
valor de observação                    0
observação de comentários            171
source_detail_url                      0
ano de origem                          0
dtype: int64

In [16]:
df_consentimento_negado.columns

Index(['indicator_label', 'descrição do indicador',
       'descrição da série de mentalidade', 'area de referencia', 'x', 'y',
       'região ODS', 'sexo', 'descrição de sexo', 'período de tempo',
       'detalhe de tempo', 'valor de observação', 'observação de comentários',
       'source_detail_url', 'ano de origem'],
      dtype='object')

In [22]:
df_negado = df_consentimento_negado[['area de referencia', 'x', 'y',
         'sexo', 'detalhe de tempo', 'valor de observação', 'observação de comentários']]
df_negado

,area de referencia,x,y,sexo,detalhe de tempo,valor de observação,observação de comentários
0,Ilhas Aland,1.980.945.969,601.544.901,M,2012-2021,18.0,Pessoas com menos de 18 anos precisam de autor...
1,Ilhas Aland,1.980.945.969,601.544.901,F,2012-2021,18.0,Pessoas com menos de 18 anos precisam de autor...
2,Albânia,2.006.660.928,4.113.897.007,M,2012-2021,18.0,NaN
3,Albânia,2.006.660.928,4.113.897.007,F,2012-2021,18.0,NaN
4,Andorra,1.576.257.417,4.254.548.611,M,2012-2021,16.0,NaN
...,...,...,...,...,...,...,...
250,Venezuela (República Bolivariana da),-6.615.642.084,7.121.324.748,F,2012-2021,18.0,NaN
251,Vietnã,105.802.499,1.009.643.079,M,2012-2021,20.0,NaN
252,Vietnã,105.802.499,1.009.643.079,F,2012-2021,18.0,NaN
253,Zimbábue,2.986.909.584,-1.900.075.492,M,2012-2021,18.0,NaN
254,Zimbábue,2.986.909.584,-1.900.075.492,F,2012-2021,18.0,NaN

In [32]:
df_casamento = pd.merge(df_consentido, df_consentimento_negado, on='região ODS')
df_casamento

,descrição da area de refêrencia,x_x,y_x,região ODS,sexo_x,detalhe de tempo_x,modificador de valor obs,valor de observação_x,observação de comentários_x,source_year,...,x_y,y_y,sexo_y,descrição de sexo,período de tempo,detalhe de tempo_y,valor de observação_y,observação de comentários_y,source_detail_url,ano de origem
0,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,2012-2021,<,18.0,NaN,2022,...,1.980.945.969,601.544.901,M,Macho,2021,2012-2021,18.0,Pessoas com menos de 18 anos precisam de autor...,https://unstats.un.org/unsd/demographic-social...,2022
1,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,2012-2021,<,18.0,NaN,2022,...,1.980.945.969,601.544.901,F,Femea,2021,2012-2021,18.0,Pessoas com menos de 18 anos precisam de autor...,https://unstats.un.org/unsd/demographic-social...,2022
2,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,2012-2021,<,18.0,NaN,2022,...,2.006.660.928,4.113.897.007,M,Macho,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
3,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,2012-2021,<,18.0,NaN,2022,...,2.006.660.928,4.113.897.007,F,Femea,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
4,Albânia,2.006.660.928,4.113.897.007,Europa e América do Norte,M,2012-2021,<,18.0,NaN,2022,...,1.576.257.417,4.254.548.611,M,Macho,2021,2012-2021,16.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10588,Uzbequistão,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,2012-2021,NaN,18.0,NaN,2022,...,8.394.678.863,2.825.866.332,M,Macho,2021,2012-2021,20.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
10589,Uzbequistão,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,2012-2021,NaN,18.0,NaN,2022,...,8.394.678.863,2.825.866.332,F,Femea,2021,2012-2021,20.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
10590,Uzbequistão,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,2012-2021,NaN,18.0,NaN,2022,...,1.147.846.389,6.134.311.134,M,Femea,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
10591,Uzbequistão,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,2012-2021,NaN,18.0,NaN,2022,...,69.294.998,3.843.069.666,M,Male,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022
10592,Uzbequistão,6.311.944.558,4.177.560.518,Ásia Central e Meridional,F,2012-2021,NaN,18.0,NaN,2022,...,69.294.998,3.843.069.666,F,Female,2021,2012-2021,18.0,NaN,https://unstats.un.org/unsd/demographic-social...,2022

In [33]:
# Exportando a base final 
df_casamento.to_csv('base_final_casamento.csv', index=False)